=== percussion/percussioncms-tools/designer/ui/src/main/resources/DTD/sys_AssemblerConfig.dtd
<?xml encoding="UTF-8"?>
<!--
   This DTD specifies the assembler configuration file.

	id - a unique number identifier.
	name - a user friendly name.
-->
<!ELEMENT AssemblerConfig (Globals, GlobalTemplates, ContextTemplates, SlotTemplates, 
   InlineLinkTemplates)>
<!--
	Specifies the location of the files which define the global variables used
	in this assembler.
-->
<!ELEMENT Globals (System, Rhythmyx?)>
<!--
	Specifies the location of the files which define the global templates used
	in this assembler.
-->
<!ELEMENT GlobalTemplates (System, Rhythmyx?)>
<!--
	Specifies the location of the files which define the templates to set context
	sensitive element informations.
-->
<!ELEMENT ContextTemplates (System, Rhythmyx?)>
<!--
	Specifies the location of the files containing the Slot templates.
-->
<!ELEMENT SlotTemplates (System, Rhythmyx?)>
<!--
	Specifies the location of the files containing the InlineLink templates.
-->
<!ELEMENT InlineLinkTemplates (System, Rhythmyx?)>
<!--
	The definitions made in system files are owned by Percussion. They can be 
	overwritten and/or extended in the Rhythmyx definitions.
-->
<!ELEMENT System (#PCDATA)>
<!--
	This is the place the user specifies his own variables, templates, etc. It
	is always imported after the System definitions, so it overwrites objects
	with the same name.
-->
<!ELEMENT Rhythmyx (#PCDATA)>

=== percussion/percussioncms-tools/htmlconverter/config/assemblerConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 1999-2021 Percussion Software, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<!DOCTYPE AssemblerConfig SYSTEM "/Rhythmyx/DTD/sys_AssemblerConfig.dtd">
<AssemblerConfig>
	<Globals>
		<System>file:sys_resources/stylesheets/assemblers/sys_Globals.xsl</System>
		<Rhythmyx>file:rx_resources/stylesheets/assemblers/rx_Globals.xsl</Rhythmyx>
	</Globals>
	<GlobalTemplates>
		<System>file:sys_resources/stylesheets/assemblers/sys_GlobalTemplates.xsl</System>
		<Rhythmyx>file:rx_resources/stylesheets/assemblers/rx_GlobalTemplates.xsl</Rhythmyx>
	</GlobalTemplates>
	<ContextTemplates>
		<System>file:sys_resources/stylesheets/assemblers/sys_ContextTemplates.xsl</System>
	</ContextTemplates>
	<SlotTemplates>
		<System>file:sys_resources/stylesheets/assemblers/sys_Slots.xsl</System>
		<Rhythmyx>file:rx_resources/stylesheets/assemblers/rx_Slots.xsl</Rhythmyx>
	</SlotTemplates>
	<InlineLinkTemplates>
		<System>file:sys_resources/stylesheets/assemblers/sys_InlineLinks.xsl</System>
		<Rhythmyx>file:rx_resources/stylesheets/assemblers/rx_InlineLinks.xsl</Rhythmyx>
	</InlineLinkTemplates>
</AssemblerConfig>
