=== percussion/percussioncms-tools/perc-deployer-client/schema/localConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~     Percussion CMS
  ~     Copyright (C) Percussion Software, Inc.  1999-2020
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU General Public License as published by
  ~     the Free Software Foundation, either version 3 of the License, or
  ~     (at your option) any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU General Public License for more details.
  ~
  ~      Mailing Address:
  ~
  ~      Percussion Software, Inc.
  ~      PO Box 767
  ~      Burlington, MA 01803, USA
  ~      +01-781-438-9900
  ~      support@percussion.com
  ~      https://www.percusssion.com
  ~
  ~     You should have received a copy of the GNU General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Ben Chen (Percussion Software) -->
<!--W3C Schema generated by XMLSPY v5 rel. 2 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="SolutionConfig">
		<xs:annotation>
			<xs:documentation>A set of related configurations.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description" minOccurs="0"/>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="property" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="propertySet" minOccurs="0" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>The name of this configuration group. e.g. RSS, Segmentation.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="SolutionConfigurations">
		<xs:annotation>
			<xs:documentation>All the configurations for a set of solutions. </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SolutionConfig" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="publisherPrefix" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>An arbitrary string used as a prefix for all names in this configuration file. Generally, it should be a name that is unique to the publisher, such as com.percussion. The same prefix should generally be used for all package configurations.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="publisherName" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Who created this package.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="description" type="xs:string">
		<xs:annotation>
			<xs:documentation>Information describing an aspect of the configuration and how to set it, including allowable values.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="entry">
		<xs:annotation>
			<xs:documentation>One element in a list.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="pvalue" type="xs:string" use="optional"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="pair">
		<xs:annotation>
			<xs:documentation>Two pieces of data that belong together.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="pvalue1" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>One part of a pair of data values. For simple content, the 'value1' attribute of the parent may be used instead.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="pvalue2" type="xs:string" minOccurs="0">
					<xs:annotation>
						<xs:documentation>The other part of a pair of data values. For simple content, the 'value2' attribute of the parent may be used instead.</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:all>
			<xs:attribute name="value1" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>This is a convenience attribute. If a left element child is not found, then this attribute is used. </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="value2" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>This is a convenience attribute. If a right element child is not found, then this attribute is used. </xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="property">
		<xs:annotation>
			<xs:documentation>A named piece of data that controls how the system behaves in some way.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description" minOccurs="0"/>
				<xs:choice>
					<xs:element ref="pvalue" minOccurs="0"/>
					<xs:element name="pvalues" minOccurs="0">
						<xs:complexType>
							<xs:choice>
								<xs:element ref="pvalue" minOccurs="0" maxOccurs="unbounded"/>
								<xs:element ref="pair" minOccurs="0" maxOccurs="unbounded"/>
							</xs:choice>
						</xs:complexType>
					</xs:element>
					<xs:element ref="propertySet" minOccurs="0" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>The name of this property. Must be unique within the enclosing parent. Case-insensitive.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>The content of the property. This is a convenience. The content may instead be placed in a child Value element. If this element has any child element, this attribute is ignored.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="action" use="optional" default="replace">
				<xs:annotation>
					<xs:documentation>This attribute only applies if the property is a collection type. Defines how these values are resolved with the collection in the design object. Most objects only support replace at this time. See the doc for each property to determine which actions are supported.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="merge">
							<xs:annotation>
								<xs:documentation>Look at the action in each entry here and perform that action against the collection/map in the target design object.
</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="replace">
							<xs:annotation>
								<xs:documentation>Remove all entries in the design object's collection and use those found here instead. Document order is maintained if the target is a list.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="propertySet">
		<xs:annotation>
			<xs:documentation>A container of properties. Generally, they are related in some way.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description" minOccurs="0"/>
				<xs:choice maxOccurs="unbounded">
					<xs:element ref="propertySet" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="property" minOccurs="0" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="action" use="optional" default="update">
				<xs:annotation>
					<xs:documentation>Only used if this element is a member of a collection. Indicates how to process this particular entry. Only certain collections support this capability. See the doc to determine what is supported. If not supported, it is ignored.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="remove">
							<xs:annotation>
								<xs:documentation>Only the key part of this set is used. If an entry in the target collection matches this key, it is removed from the target. Otherwise, this entry is skipped.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="update">
							<xs:annotation>
								<xs:documentation>If an entry in the target collection matches this key, it is updated to match this entry. Otherwise, a new entry is added.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>If this element needs to be referenced from the configuration definition, then a name should be supplied, otherwise one is not needed, but may be provided if it improves readability. A name is required if this element is a child of SolutionConfig.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="pvalue" type="xs:string">
		<xs:annotation>
			<xs:documentation>The content of some property. For single-valued, simple content, the 'value' attribute of the parent may be used instead.</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>

=== percussion/percussioncms-tools/perc-deployer-client/src/test/resources/com/percussion/rx/config/test/PSTemplateSetterTest_localConfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~     Percussion CMS
  ~     Copyright (C) Percussion Software, Inc.  1999-2020
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU General Public License as published by
  ~     the Free Software Foundation, either version 3 of the License, or
  ~     (at your option) any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU General Public License for more details.
  ~
  ~      Mailing Address:
  ~
  ~      Percussion Software, Inc.
  ~      PO Box 767
  ~      Burlington, MA 01803, USA
  ~      +01-781-438-9900
  ~      support@percussion.com
  ~      https://www.percusssion.com
  ~
  ~     You should have received a copy of the GNU General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<SolutionConfigurations publisherPrefix="com.percussion" publisherName="Percussion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="localConfig.xsd">
   <SolutionConfig name="RSS">
      <!-- Basic Properties -->
      <property name="label" value="My-Label"/>
      <property name="globalTemplate" value="rffGtEnterpriseInvestmentsCommon"/>
      <property name="globalTemplateUsage" value="None"/>
      <property name="publishWhen" value="Never"/>
      <property name="mimeType" value="text/xml"/>
      <property name="charset" value="UTF-16"/>
      <property name="locationPrefix" value="TestPrefix"/>
      <property name="locationSuffix" value="TestSuffix"/>
      <property name="bindingSet">
            <!-- If you want to expose all bindings, add them like this in the default
		      config. If the user wants to add/remove any bindings, they would copy this
		      entire node to their local config and make the desired changes. See later
		      in this file for other ways of exposing bindings to configuration. -->      
         <pvalues>
            <pair value1="$rxs_navbase_1" value2="$sys.variables.rxs_navbase_1"/>
            <pair value1="$rxs_navbase" value2="$sys.variables.rxs_navbase"/>
            <pair value1="$rxs_navbase_2" value2="$sys.variables.rxs_navbase_2"/>
         </pvalues>
      </property>
      
      <propertySet name="bindings">
      	<!-- If you want to expose merge some bindings, add them like this -->
         <property name="$rxs_navbase_1" value="$sys.variables.rxs_navbase_1"/>
         <property name="$rxs_navbase_2" value="$sys.variables.rxs_navbase_2"/>
         <property name="binding_sequence">
	         <pvalues>
	            <pvalue>$rxs_navbase_1</pvalue>
	            <pvalue>$rxs_navbase</pvalue>
	            <pvalue>$$rxs_navbase_2</pvalue>
	         </pvalues>
         </property>
      </propertySet>

   </SolutionConfig>
</SolutionConfigurations>

=== percussion/percussioncms-tools/perc-deployer-client/src/test/resources/com/percussion/rx/config/test/PSContentListSetterTest_DefaultConfigs.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~     Percussion CMS
  ~     Copyright (C) Percussion Software, Inc.  1999-2020
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU General Public License as published by
  ~     the Free Software Foundation, either version 3 of the License, or
  ~     (at your option) any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU General Public License for more details.
  ~
  ~      Mailing Address:
  ~
  ~      Percussion Software, Inc.
  ~      PO Box 767
  ~      Burlington, MA 01803, USA
  ~      +01-781-438-9900
  ~      support@percussion.com
  ~      https://www.percusssion.com
  ~
  ~     You should have received a copy of the GNU General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<SolutionConfigurations publisherPrefix="com.percussion" publisherName="Percussion"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="localConfig.xsd">
   <SolutionConfig name="RSS">

<!---  ========================================
        Content List        "rffCiFullBinary"      
        =========================================
-->
      <property name="deliveryType" value="filesystem"/>
      <property name="filter" value="public"/>
      <property name="generator" value="Java/global/percussion/system/sys_SearchGenerator"/>
      <propertySet name="generatorParams">
      	<property name="query" value="select rx:sys_contentid, rx:sys_folderid from rx:rfffile,rx:rffimage,rx:percnavimage where jcr:path like '//Sites/CorporateInvestments%'"/>
      </propertySet>
      <property name="expander" value="Java/global/percussion/system/sys_SiteTemplateExpander"/>
      <propertySet name="expanderParams">
      </propertySet>
   </SolutionConfig>
</SolutionConfigurations>

=== percussion/percussioncms-tools/perc-deployer-client/src/test/resources/com/percussion/rx/config/test/PSSiteSetterTest_defaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~     Percussion CMS
  ~     Copyright (C) Percussion Software, Inc.  1999-2020
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU General Public License as published by
  ~     the Free Software Foundation, either version 3 of the License, or
  ~     (at your option) any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU General Public License for more details.
  ~
  ~      Mailing Address:
  ~
  ~      Percussion Software, Inc.
  ~      PO Box 767
  ~      Burlington, MA 01803, USA
  ~      +01-781-438-9900
  ~      support@percussion.com
  ~      https://www.percusssion.com
  ~
  ~     You should have received a copy of the GNU General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<SolutionConfigurations publisherPrefix="com.percussion" publisherName="Percussion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="localConfig.xsd">
   <SolutionConfig name="RSS">

<!---  ========================================
        Site        "Corporate_Investments"      
        =========================================
-->
		<!--  Various properties for the "SiteVaraibleSetter" -->
		
		<property name="ciName" value="Corporate_Investments"/>

		<property name="ciNameList">
			<pvalues>
				<pvalue>Corporate_Investments</pvalue>
			</pvalues>
		</property>		

		<property name="ci_ei_Names">
			<pvalues>
				<pvalue>Corporate_Investments</pvalue>
				<pvalue>Enterprise_Investments</pvalue>
			</pvalues>
		</property>		
      
      <property name="siteVariables_CI"> 
         <description>Site variables apply to CI Site.</description>
         <propertySet>
		      <property name="name"  value="rxs_urlroot"/>
		      <property name="context"  value="Site_Folder_Assembly"/>
		      <property name="value"  value="/CI_Home"/>
         </propertySet>
         <propertySet>
		      <property name="name"  value="rxs_navbase"/>
		      <property name="context"  value="Preview"/>
		      <property name="value"  value="../web_resources/corporate_investments"/>
         </propertySet>
         <propertySet>
		      <property name="name"  value="rxs_navbase"/>
		      <property name="context"  value="Site_Folder_Assembly"/>
		      <property name="value"  value="/CI_Home/resources"/>
         </propertySet>
      </property>

		<!--  Properties for the CI Site -->
	
      <property name="CmsPath" value="//Sites/CorporateInvestments" />
      <property name="PublishedPath" value="../CI_Home.war" />
      <property name="PublishedUrl" value="http://127.0.0.1:9992/CI_Home" />
      <property name="globalTemplateName" value="rffGtCorporateInvestmentsCommon" />
      <!-- optionally used a propertySet to group the ftp related params -->
      <propertySet name="ftp">
         <property name="IpAddress" value="127.0.0.1" />
         <property name="Port" value="21" />
         <property name="UserId" value="" />
         <property name="Password" value="" />
      </propertySet>
      <property name="UnpublishFlags" value="u" />
      <property name="AllowedNamespaces" value="" />
      <property name="NavTheme" value="" />

   </SolutionConfig>
</SolutionConfigurations>

=== percussion/percussioncms-tools/perc-deployer-client/src/test/resources/com/percussion/rx/config/test/PSRelationshipConfigSetterTest_localConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~     Percussion CMS
  ~     Copyright (C) Percussion Software, Inc.  1999-2020
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU General Public License as published by
  ~     the Free Software Foundation, either version 3 of the License, or
  ~     (at your option) any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU General Public License for more details.
  ~
  ~      Mailing Address:
  ~
  ~      Percussion Software, Inc.
  ~      PO Box 767
  ~      Burlington, MA 01803, USA
  ~      +01-781-438-9900
  ~      support@percussion.com
  ~      https://www.percusssion.com
  ~
  ~     You should have received a copy of the GNU General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<SolutionConfigurations publisherPrefix="com.percussion" publisherName=" Percussion"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="localConfig.xsd">
	<SolutionConfig name="PSRelationshipConfigTest">
		<propertySet name="deepCloning">
			<property name="enabled" value="true"/>
			<property name="condition">
				<propertySet>
					<property name="type" value="Conditional"/>
					<property name="rules">
						<propertySet>
							<property name="variable1" value="PSXOriginatingRelationshipProperty/name"/>
							<property name="variable2" value="Translation-Mandatory"/>
							<property name="operator" value="="/>
							<property name="boolean" value="AND"/>
						</propertySet>
						<propertySet>
							<property name="variable1" value="PSXSingleHTMLParameter/sys_communityid"/>
							<property name="variable2" value="1001"/>
							<property name="operator" value="="/>
							<property name="boolean" value="AND"/>
						</propertySet>
					</property>
					<property name="boolean" value="AND"/>
				</propertySet>
			</property>
		</propertySet>
		<propertySet name="shallowCloning">
			<property name="enabled" value="true"/>
			<property name="condition">
				<propertySet>
					<property name="type" value="Conditional"/>
					<property name="rules">
						<propertySet>
							<property name="variable1" value="PSXOriginatingRelationshipProperty/name"/>
							<property name="variable2" value="Translation-Mandatory"/>
							<property name="operator" value="="/>
							<property name="boolean" value="AND"/>
						</propertySet>
						<propertySet>
							<property name="variable1" value="PSXSingleHTMLParameter/sys_communityid"/>
							<property name="variable2" value="1001"/>
							<property name="operator" value="="/>
							<property name="boolean" value="AND"/>
						</propertySet>
					</property>
					<property name="boolean" value="AND"/>
				</propertySet>
				<propertySet>
					<property name="type" value="Extension"/>
					<property name="name" value="Java/global/percussion/generic/sys_OverrideLiteral"/>
					<property name="extensionParams">
						<pvalues>
							<pvalue>PSXSingleHTMLParameter/sys_contentid</pvalue>
							<pvalue>1001</pvalue>
						</pvalues>
					</property>
					<property name="boolean" value="AND"/>
				</propertySet>
			</property>
		</propertySet>
		<property name="fieldOverrides">
			<propertySet>
				<property name="fieldName" value="displaytitle"/>
				<property name="extension" value="Java/global/percussion/generic/sys_OverrideLiteral"/>
				<property name="extensionParams">
					<pvalues>
						<pvalue>PSXContentItemStatus/CONTENTSTATUS.TITLE</pvalue>
						<pvalue>displaytitle</pvalue>
					</pvalues>
				</property>
			</propertySet>
		</property>
		<property name="effects">
			<propertySet>
				<property name="executionContext">
					<pvalues>
						<pvalue>Pre-Construction</pvalue>
						<pvalue>Pre-Destruction</pvalue>
					</pvalues>
				</property>
				<property name="direction" value="Up"/>
                		<property name="extension" value="Java/global/percussion/relationship/effect/sys_PublishMandatory"/>
				<property name="extensionParams">
					<pvalues>
						<pvalue>PSXSingleHTMLParameter/sys_contentid</pvalue>
						<pvalue>1001</pvalue>
					</pvalues>
				</property>
				<property name="condition">
					<propertySet>
						<property name="type" value="Conditional"/>
						<property name="rules">
							<propertySet>
								<property name="variable1" value="PSXSingleHTMLParameter/sys_communityid"/>
								<property name="variable2" value="1001"/>
								<property name="operator" value="="/>
								<property name="boolean" value="AND"/>
							</propertySet>
							<propertySet>
								<property name="variable1" value="PSXSingleHTMLParameter/sys_contentid"/>
								<property name="variable2" value="1001"/>
								<property name="operator" value="="/>
								<property name="boolean" value="AND"/>
							</propertySet>
						</property>
						<property name="boolean" value="AND"/>
					</propertySet>
					<propertySet>
						<property name="type" value="Extension"/>
						<property name="name" value="Java/global/percussion/generic/sys_OverrideLiteral"/>
						<property name="extensionParams">
							<pvalues>
								<pvalue>PSXSingleHTMLParameter/sys_contentid</pvalue>
								<pvalue>1001</pvalue>
							</pvalues>
						</property>
						<property name="boolean" value="AND"/>
					</propertySet>
				</property>
			</propertySet>
		</property>
	</SolutionConfig>
</SolutionConfigurations>

=== percussion/percussioncms-tools/perc-deployer-client/src/test/resources/com/percussion/rx/config/test/PSSiteTemplateVisibilitySetterTest_defaultConfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~     Percussion CMS
  ~     Copyright (C) Percussion Software, Inc.  1999-2020
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU General Public License as published by
  ~     the Free Software Foundation, either version 3 of the License, or
  ~     (at your option) any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU General Public License for more details.
  ~
  ~      Mailing Address:
  ~
  ~      Percussion Software, Inc.
  ~      PO Box 767
  ~      Burlington, MA 01803, USA
  ~      +01-781-438-9900
  ~      support@percussion.com
  ~      https://www.percusssion.com
  ~
  ~     You should have received a copy of the GNU General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<SolutionConfigurations publisherPrefix="com.percussion" publisherName="Percussion"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="localConfig.xsd">
   <SolutionConfig name="RSS">
      <!-- Basic Properties -->
      <property name="label" value="P - CI Generic"/>
      <property name="globalTemplate" value="rffGtCorporateInvestmentsCommon"/>
      <property name="globalTemplateUsage" value="Default"/>
      <property name="publishWhen" value="Default"/>
      <property name="bindingSet">
         <pvalues>
            <pair value1="$rxs_navbase" value2="$sys.variables.rxs_navbase"/>
            <pair value1="$rxs_navbase_1" value2="$sys.variables.rxs_navbase_1"/>
            <pair value1="$rxs_navbase_2" value2="$sys.variables.rxs_navbase_2"/>
<!--            
-->            
         </pvalues>
      </property>

		<property name="ci_or_allSites">
			<pvalues>
				<pvalue>Corporate_Investments</pvalue>
			</pvalues>
		</property>		
      
      <property name="visibility">
      		<pvalues>
       		    <pvalue>rffPgCiGeneric</pvalue>
      		</pvalues>
      </property>

   </SolutionConfig>
</SolutionConfigurations>

=== percussion/percussioncms-tools/perc-deployer-client/src/test/resources/com/percussion/rx/config/test/PSLocationSchemeSetterTest_2_previous_localConfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~     Percussion CMS
  ~     Copyright (C) Percussion Software, Inc.  1999-2020
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU General Public License as published by
  ~     the Free Software Foundation, either version 3 of the License, or
  ~     (at your option) any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU General Public License for more details.
  ~
  ~      Mailing Address:
  ~
  ~      Percussion Software, Inc.
  ~      PO Box 767
  ~      Burlington, MA 01803, USA
  ~      +01-781-438-9900
  ~      support@percussion.com
  ~      https://www.percusssion.com
  ~
  ~     You should have received a copy of the GNU General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<SolutionConfigurations publisherPrefix="com.percussion" publisherName="Percussion"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="localConfig.xsd">
   <SolutionConfig name="RSS">

<!---  ========================================================
        Location Scheme        "Publish / CI_Home_ExtraOne"      
        Location Scheme        "Site_Folder_Assembly / CI_Home_ExtraOne"      
        =======================================================
-->
	
		<property name="contexts">
			<pvalues>
	      	<pvalue>Publish</pvalue>
	      	<pvalue>Site_Folder_Assembly</pvalue>
			</pvalues>
		</property>
		
		<property name="description" value="CI Home page location å¤©å¤©"/>
      <property name="expression"  value="/index.html"/>
						
   </SolutionConfig>
</SolutionConfigurations>
