=== percussion/percussioncms-tools/designer/ui/src/main/resources/com/percussion/workbench/ui/views/viewHierarchyDef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Paul Howard (Percussion Software) -->
<!-- edited with XMLSpy v2006 sp1 U (http://www.altova.com) by Paul Howard (Percussion Software) -->
<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
   <xs:element name="Catalog">
      <xs:annotation>
         <xs:documentation>A Catalog defines a way to determine a set of containers and leaves at run time. </xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="CatalogProperty" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="Handler" minOccurs="0"/>
            <xs:element ref="Node" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="Catalog" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attribute name="type" use="optional" default="object">
            <xs:simpleType>
               <xs:restriction base="xs:NMTOKEN">
                  <xs:enumeration value="class">
                     <xs:annotation>
                        <xs:documentation>If this type is chosen, the name attibute must specify a class name that extends the PSCatalogFactoryBase class. This class is then responsible for performing the catalog.</xs:documentation>
                     </xs:annotation>
                  </xs:enumeration>
                  <xs:enumeration value="object">
                     <xs:annotation>
                        <xs:documentation>This type causes the system to automatically catalog all instances of the type whose string id is provided in the name attribute. This must be the string representation of an Enum value (e.g.PSObjectTypes) that represents the primary type. This value is passed to the PSCoreFactory to obtain the model for cataloging.</xs:documentation>
                     </xs:annotation>
                  </xs:enumeration>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attribute name="name" type="xs:string" use="optional">
            <xs:annotation>
               <xs:documentation>The meaning of this attribute varies depending on the value of the type attribute.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="model" type="xs:string"/>
         <xs:attribute name="allowedTypes" use="optional">
            <xs:annotation>
               <xs:documentation>Allows the designer to limit the object types that can be placed in this folder. A list of object type ids as defined in the workbench core code. Any unrecognized ids are ignored. Ids are case-sensitive. If not provided, all types are allowed. The handler of this class will inherit these types if it doesn't provide its own.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:NMTOKENS"/>
            </xs:simpleType>
         </xs:attribute>
         <xs:attribute name="defaultInstanceTree" type="xs:boolean" default="true">
            <xs:annotation>
               <xs:documentation>Allows the designer to override the default behavior of substituting the nodes of the InstanceTree that has a matching object type. If the node has no other children, the children from a matching InstanceTree will be used unless this value is false.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="isReference" type="xs:boolean" use="optional" default="false"/>
         <xs:attribute name="displayLabelSource" use="optional" default="objectName">
            <xs:annotation>
               <xs:documentation>See the same named attribute of the Node element. Behavior is identical except the labelKey value is not allowed.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:NMTOKEN">
                  <xs:enumeration value="objectName"/>
                  <xs:enumeration value="objectLabel"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
         <xs:attribute name="catalogObjectTypes" type="xs:NMTOKENS" use="optional">
            <xs:annotation>
               <xs:documentation>If 2 or more sibling Catalog nodes are present, then this attribute must be specified. It should include a space-delimited list of the object types that this catalog generates, just like the allowedTypes attribute. These values must be the string representation of the PSObjectType.toSerial() method.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="CatalogProperty">
      <xs:annotation>
         <xs:documentation>This property is inherited by all Catalog nodes that are descendents of the parent node.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string">
               <xs:attribute name="name" type="xs:string" use="required"/>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="Description" type="xs:string"/>
   <xs:element name="InstanceTree">
      <xs:annotation>
         <xs:documentation>Definitions for specific design object types that can be shared.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="Handler" minOccurs="0"/>
            <xs:choice minOccurs="0">
               <xs:sequence>
                  <xs:element ref="Node" maxOccurs="unbounded"/>
               </xs:sequence>
               <xs:sequence>
                  <xs:element ref="Catalog" maxOccurs="unbounded"/>
               </xs:sequence>
            </xs:choice>
         </xs:sequence>
         <xs:attribute name="objectIds" type="xs:NMTOKENS" use="required">
            <xs:annotation>
               <xs:documentation>This is the string representation of 1 or more object type(s) for which this fragment will be used. See PSObjectTypes for examples. If a node in the tree def has this object type and it doesn't have any declared children, then the children of this node will be used as its children. Otherwise, if the node does have children, then the instance definition will be ignored. The instance tree can also be overridden by setting the defaultInstanceTree attribute of the Catalog element to false. This allows the node to have no children w/o using a catalog factory that returns an empty set.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="sorting" type="xs:NMTOKEN" default="document">
            <xs:annotation>
               <xs:documentation>If there is a mixture of Nodes and Catalogs, then 'document' type is not supported. In that case, ascending will be used unless descending is specified. Containers are sorted before leaves for ascending and after for descending.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="displayLabelSource" use="optional" default="objectName">
            <xs:annotation>
               <xs:documentation>See the same-named attribute on the Catalog node for description.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:NMTOKEN">
                  <xs:enumeration value="objectName"/>
                  <xs:enumeration value="objectLabel"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="Node">
      <xs:annotation>
         <xs:documentation>A Node specifies a single folder or leaf.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="NodeProperty" minOccurs="0" maxOccurs="unbounded">
               <xs:annotation>
                  <xs:documentation>Name/value pairs that are passed through to users of the PSUiRefernce node. They are not used by the declarative framework in any way. Generally, they are used to provide information about a node rather than relying on the name of the node. The content is the value. Unlike CatalogProperties, these are not inherited.</xs:documentation>
               </xs:annotation>
               <xs:complexType>
                  <xs:simpleContent>
                     <xs:extension base="xs:string">
                        <xs:attribute name="name" type="xs:string" use="required"/>
                     </xs:extension>
                  </xs:simpleContent>
               </xs:complexType>
            </xs:element>
            <xs:element name="HomeNodeProperty" minOccurs="0" maxOccurs="unbounded">
               <xs:annotation>
                  <xs:documentation>If the homeTypeClassName attribute in the Node parent is specified, all of these are passed to the sorting method. The content is the value of the property.</xs:documentation>
               </xs:annotation>
               <xs:complexType>
                  <xs:simpleContent>
                     <xs:extension base="xs:string">
                        <xs:attribute name="name" type="xs:string" use="required"/>
                     </xs:extension>
                  </xs:simpleContent>
               </xs:complexType>
            </xs:element>
            <xs:element ref="CatalogProperty" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="Description" minOccurs="0"/>
            <xs:element ref="Handler" minOccurs="0">
               <xs:annotation>
                  <xs:documentation>If a node needs special handling, a custom class can be provided that implements a pre-defined interface.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element ref="Node" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element ref="Catalog" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attribute name="labelKey" type="xs:string" use="required">
            <xs:annotation>
               <xs:documentation>This is a key into the I18N bundle. If no entry is found in the bundle, the key will be used as the label for the node.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="preferences" type="xs:string"/>
         <xs:attribute name="objectId" type="xs:string"/>
         <xs:attribute name="allowedTypes" type="xs:NMTOKENS" use="optional">
            <xs:annotation>
               <xs:documentation>Identical to the same named node on the Catalog element. See that attribute's description for details.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="sorting" type="xs:NMTOKEN" default="document">
            <xs:annotation>
               <xs:documentation>Specifies how the children of this node should be ordered. If there is a mixture of Nodes and Catalogs, then 'document' type is not supported. In that case, ascending will be used unless descending is specified. Containers are sorted before leaves for ascending and after for descending.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="objectHomeType" type="xs:string">
            <xs:annotation>
               <xs:documentation>If this node is the 'home node' for some type of object, such as slots, then this attribute will have the object type. It should be the string representation of the PSObjectType (e.g. SLOT.) If a new object is created and the user doesn't specify a specific location, then it will be placed here. There should only be 1 home node per object type within the design views.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="homeTypeClassName" type="xs:string" use="optional">
            <xs:annotation>
               <xs:documentation>The name of a class that implements the IPSHomeNodeManager interface. If multiple nodes have an objectHomeType defined, this attribute must be present. The class is used to determine which node gets an instance of that home object type.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="treeName" type="xs:string" use="optional">
            <xs:annotation>
               <xs:documentation>If this node supports the creation of new USER_FILE folders, then this value must be supplied. It specifies the name of the element at the root of the associated tree. Each node that has such a sub-structure should use a different tree.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="displayLabelSource" use="optional" default="labelKey">
            <xs:annotation>
               <xs:documentation>Controls what text is used as the label within the UI tree. </xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:NMTOKEN">
                  <xs:enumeration value="labelKey">
                     <xs:annotation>
                        <xs:documentation>Use the value specified in the labelKey attribute, even if an objectId is supplied. If an object is supplied and no labelKey is supplied, then the object name is used.</xs:documentation>
                     </xs:annotation>
                  </xs:enumeration>
                  <xs:enumeration value="objectName">
                     <xs:annotation>
                        <xs:documentation>Use the associated object's name.</xs:documentation>
                     </xs:annotation>
                  </xs:enumeration>
                  <xs:enumeration value="objectLabel">
                     <xs:annotation>
                        <xs:documentation>Use the associated object's label.</xs:documentation>
                     </xs:annotation>
                  </xs:enumeration>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="TreeDef">
      <xs:annotation>
         <xs:documentation>The root node.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="InstanceTree" minOccurs="0" maxOccurs="unbounded"/>
            <xs:choice>
               <xs:sequence>
                  <xs:element ref="Node" maxOccurs="unbounded"/>
               </xs:sequence>
               <xs:sequence>
                  <xs:element ref="Catalog"/>
               </xs:sequence>
            </xs:choice>
         </xs:sequence>
         <xs:attribute name="sorting" default="document">
            <xs:annotation>
               <xs:documentation>If there is a mixture of Nodes and Catalogs, then 'document' type is not supported. In that case, ascending will be used unless descending is specified. Containers are sorted before leaves for ascending and after for descending.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:NMTOKEN">
                  <xs:enumeration value="document"/>
                  <xs:enumeration value="ascending"/>
                  <xs:enumeration value="descending"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="Handler">
      <xs:annotation>
         <xs:documentation>If a node needs special handling, a custom class can be provided that implements a pre-defined interface.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:attribute name="className" type="xs:string" use="optional">
            <xs:annotation>
               <xs:documentation>Java class name of a class that implements the IPSDeclarativeNodeHandler interface. The children of this node will be supplied to the ctor when the class is instantiated, along w/ any catalog properties that ancestors have. If not provided, the PSIconNodeHandler is used.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="allowedTypes" type="xs:NMTOKENS" use="optional">
            <xs:annotation>
               <xs:documentation>Identical to the same named node on the Catalog element. See that attribute's description for details.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
         <xs:attribute name="iconPath" type="xs:string"/>
         <xs:attribute name="securable" type="xs:boolean" use="optional" default="true"/>
         <xs:attribute name="copyable" type="xs:boolean" use="optional" default="true"/>
         <xs:attribute name="deletable" type="xs:boolean" use="optional" default="true"/>
         <xs:attribute name="renamable" type="xs:boolean" use="optional" default="true"/>
         <xs:attribute name="pasteable" type="xs:boolean" use="optional" default="true"/>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== percussion/percussioncms-tools/designer/ui/src/main/resources/com/percussion/workbench/ui/views/hierarchy/catalogTreeTest_viewHierarchyDef.xml
<!--
This is a test file for use by the PSDeclarativeHierarchyTest.java class.
It provides several tree fragments composed of Nodes and Catalogs. 
-->
<TreeDef sorting="document" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\paulhoward\My Documents\viewHierarchyDef.xsd">
   <InstanceTree objectIds="SLOT">
      <Handler iconPath="icons/slot16.gif"/>
      <Node labelKey="Slot sub-folder"/>
   </InstanceTree>
   <Node 
      labelKey="Cataloged Slots"
      allowedTypes="USER_FILE:WORKBENCH_FOLDER TEMPLATE:SHARED"
      >
      <!-- catalogs 3 deep -->
      <Handler 
         className="com.percussion.workbench.ui.views.hierarchy.TestHandler" 
         iconPath="icons/slot16.gif"
         />
      <Catalog type="object" name="SLOT">
         <Handler 
            className="com.percussion.workbench.ui.views.hierarchy.TestHandler" 
            allowedTypes="com.percussion.client.PSObjectTypes$1:SLOT"
            iconPath="icons/slot16.gif"
            />
         <Catalog type="class" name="com.percussion.workbench.ui.views.hierarchy.TestCataloger">
            <CatalogProperty name="group">1</CatalogProperty>
            <Catalog type="class" name="com.percussion.workbench.ui.views.hierarchy.TestCataloger">
               <CatalogProperty name="subgroup">1</CatalogProperty>
            </Catalog>
         </Catalog>
      </Catalog>
   </Node>
   <Node labelKey="Root node 2">
      <!-- Mixture of multiple nodes and multiple catalogs -->
      <Handler 
         iconPath="icons/slot16.gif"
         />
      <Node labelKey="xmixed node 1">
         <!-- add child so parent is treated as folder, not leaf -->
         <Node labelKey="child1"/>
      </Node>
      <Node labelKey="mixed node 2">
         <!-- add child so parent is treated as folder, not leaf -->
         <Node labelKey="child1"/>
      </Node>
      <Catalog type="class" name="com.percussion.workbench.ui.views.hierarchy.TestCataloger">
         <CatalogProperty name="mixed">group1</CatalogProperty>
      </Catalog>
      <Catalog type="class" name="com.percussion.workbench.ui.views.hierarchy.TestCataloger">
         <CatalogProperty name="mixed">group2</CatalogProperty>
      </Catalog>
   </Node>
   <Node labelKey="Root node 3">
      <!-- alternating nodes and catalogs -->
      <CatalogProperty name="scope">37</CatalogProperty>
      <Node labelKey="child1">
         <Catalog type="class" name="com.percussion.workbench.ui.views.hierarchy.TestCataloger">
            <CatalogProperty name="alternating">1</CatalogProperty>
            <CatalogProperty name="prop2">21</CatalogProperty>
            <Node labelKey="catalog child1">
               <Catalog type="class" name="com.percussion.workbench.ui.views.hierarchy.TestCataloger">
                  <CatalogProperty name="alternating">2</CatalogProperty>
               </Catalog>
            </Node>
         </Catalog>
      </Node>
   </Node>
   <Node 
      labelKey="Root node 4"
      allowedTypes="com.percussion.client.PSObjectTypes$1:USER_FILE:com.percussion.client.PSObjectTypes$UserFileSubTypes:WORKBENCH_FOLDER"
      >
      <!-- context parent -->
      <Catalog type="object" name="SLOT">
         <Node labelKey="context parent test">
            <Catalog type="class" name="com.percussion.workbench.ui.views.hierarchy.TestCataloger">
               <CatalogProperty name="ctxparent">1</CatalogProperty>
            </Catalog>
         </Node>
      </Catalog>
   </Node>
   <Node 
      labelKey="Root node 5"
      allowedTypes="com.percussion.client.PSObjectTypes$1:COMMUNITY"
      >
      <!-- context parent -->
      <Catalog 
         type="object" 
         name="SLOT"
         allowedTypes="com.percussion.client.PSObjectTypes$1:TEMPLATE:SHARED"
         >
         <Node labelKey="context parent test">
            <Catalog type="class" name="com.percussion.workbench.ui.views.hierarchy.TestCataloger">
               <CatalogProperty name="ctxparent">1</CatalogProperty>
            </Catalog>
         </Node>
      </Catalog>
   </Node>
</TreeDef>

=== percussion/percussioncms-tools/designer/ui/src/main/resources/com/percussion/workbench/ui/views/hierarchy/instanceTreeTest_viewHierarchyDef.xml
<!--
This is a test file for use by the PSDeclarativeHierarchyTest.java class.
It provides a simple tree that has children that will use Instance nodes.
-->
<TreeDef sorting="document" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Documents and Settings\paulhoward\My Documents\viewHierarchyDef.xsd">
   <InstanceTree objectIds="SLOT">
      <Node labelKey="Contained Templates">
         <Description/>
         <Catalog type="class" name="com.percussion.workbench.ui.views.hierarchy.TestCataloger">
            <CatalogProperty name="expansionType">variantLinks</CatalogProperty>
         </Catalog>
      </Node>
   </InstanceTree>
   <Node labelKey="Node 1">
      <Catalog type="object" name="SLOT"/>
   </Node>
   <Node labelKey="Node 2">
      <Catalog type="object" name="SLOT" defaultInstanceTree="false"/>
   </Node>
   <Node labelKey="Node 3">
      <Catalog type="object" name="SLOT">
         <Catalog type="class" name="com.percussion.workbench.ui.views.hierarchy.TestCataloger">
            <CatalogProperty name="slotInstanceOverride">1</CatalogProperty>
         </Catalog>
      </Catalog>
   </Node>
   <Node labelKey="Node 4">
      <CatalogProperty name="inherited">2</CatalogProperty>
      <Catalog type="object" name="SLOT"/>
   </Node>
</TreeDef>

=== percussion/percussioncms-tools/designer/ui/src/main/resources/com/percussion/workbench/ui/views/widget_content_viewHierarchyDef.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file defines the structure for the Rhythmyx workbench 'Content Design' 
view. This view shows all the content related objects in a tree structure as
described in the functional specification.
-->
<TreeDef sorting="document" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="viewHierarchyDef.xsd">
   <InstanceTree objectIds="CONTENT_TYPE">
      <Handler 
         className="com.percussion.workbench.ui.handlers.PSDeclarativeNodeHandler"
         iconPath="icons/contentType16.gif"
         />
      <Node labelKey="Allowed Workflows" sorting="ascending">
         <Description/>
         <Handler 
            className="com.percussion.workbench.ui.handlers.PSContentTypeAllowedWorkflowNodeHandler" 
            allowedTypes="WORKFLOW"
            />
         <Catalog 
            type="class" 
            name="com.percussion.workbench.ui.catalogs.canonical.PSContentTypeExpansionFactory"
            isReference="true"
            >
            <CatalogProperty name="expansionType">workflow</CatalogProperty>
         </Catalog>
      </Node>
      <Node labelKey="Allowed Templates and XSL Variants" sorting="ascending">
         <NodeProperty name="childType">templateLinkedToContentType</NodeProperty>
         <Description/>
         <Handler 
            className="com.percussion.workbench.ui.handlers.PSContentTypeAssociateTemplateNodeHandler" 
            allowedTypes="TEMPLATE:SHARED TEMPLATE:LOCAL TEMPLATE:VARIANT"
            />
         <Catalog 
            type="class" 
            name="com.percussion.workbench.ui.catalogs.canonical.PSContentTypeExpansionFactory"
            isReference="true"
            >
            <CatalogProperty name="expansionType">linkedSharedTemplates</CatalogProperty>
         </Catalog>
      </Node>
   </InstanceTree>
   <InstanceTree objectIds="USER_FILE:WORKBENCH_FOLDER">
      <Handler 
      	className="com.percussion.workbench.ui.handlers.PSNavigationObjectNodeHandler"
         allowedTypes="USER_FILE:WORKBENCH_FOLDER CONTENT_TYPE"
         securable="false"
      	/>
      <Catalog type="object" name="USER_FILE"/>
   </InstanceTree>
   <InstanceTree objectIds="TEMPLATE:SHARED TEMPLATE:VARIANT TEMPLATE:LOCAL">
      <Handler 
         className="com.percussion.workbench.ui.handlers.PSRefNodeHandler" 
         iconPath="icons/template16.gif"
         />
   </InstanceTree>
   <InstanceTree objectIds="SLOT">
      <Handler 
         className="com.percussion.workbench.ui.handlers.PSRefNodeHandler" 
         iconPath="icons/slot16.gif"
         />
   </InstanceTree>
   <InstanceTree objectIds="KEYWORD">
      <Handler 
         className="com.percussion.workbench.ui.handlers.PSDeclarativeNodeHandler"
         iconPath="icons/keyword16.gif"
         />
   </InstanceTree>
   <InstanceTree objectIds="LOCALE">
      <Handler 
            className="com.percussion.workbench.ui.handlers.PSDeclarativeNodeHandler"
            iconPath="icons/locale16.gif"
            renamable="false"
            />
   </InstanceTree>
   <InstanceTree objectIds="WORKFLOW">
      <Handler 
            className="com.percussion.workbench.ui.handlers.PSRefNodeHandler"
            iconPath="icons/workflow16.gif"
            />
   </InstanceTree>
   <InstanceTree objectIds="SHARED_FIELDS">
      <Handler
         className="com.percussion.workbench.ui.handlers.PSDeclarativeNodeHandler"
         copyable="false"
         securable="false"
         iconPath="icons/ce_sharedFile16.gif"
         />
   </InstanceTree>
   <Node 
      labelKey="Content Types" 
      objectHomeType="CONTENT_TYPE" 
      treeName="contenttypes"
      sorting="ascending"
      >
      <Description>Contains the design objects that define named groupings of fields and how they are rendered.</Description>
      <Handler 
         className="com.percussion.workbench.ui.handlers.PSContentTypesNodeHandler"
			allowedTypes="USER_FILE:WORKBENCH_FOLDER CONTENT_TYPE"
      	/>
      <Catalog 
      	   type="object" 
      	   name="USER_FILE" 
            allowedTypes="USER_FILE:WORKBENCH_FOLDER CONTENT_TYPE"
            catalogObjectTypes="USER_FILE:WORKBENCH_FOLDER"
      	   >
      </Catalog>
      <Catalog 
            type="class" 
            name="com.percussion.workbench.ui.catalogs.canonical.PSContentTypeCatalogFactory"
            catalogObjectTypes="CONTENT_TYPE"
            >
         <CatalogProperty name="contentTypeCategory">uncategorized</CatalogProperty>
      </Catalog>
   </Node>
   <Node labelKey="Keywords" objectHomeType="KEYWORD" sorting="ascending">
      <Description/>
      <Handler 
         className="com.percussion.workbench.ui.handlers.PSDropCopyNodeHandler"
         allowedTypes="KEYWORD"
         />
      <Catalog type="object" name="KEYWORD">
         <Catalog type="class" name="com.percussion.workbench.ui.catalogs.canonical.PSKeywordExpansionFactory"/>
      </Catalog>
   </Node>
   <Node labelKey="Shared Fields" objectHomeType="SHARED_FIELDS" sorting="ascending">
      <Description/>
      <Handler 
         className="com.percussion.workbench.ui.handlers.PSDropCopyNodeHandler"
			allowedTypes="SHARED_FIELDS"
      	/>
      <Catalog type="class" name="com.percussion.workbench.ui.catalogs.canonical.PSSharedFieldsCatalogFactory">
         <Catalog type="class" name="com.percussion.workbench.ui.catalogs.canonical.PSSharedFieldsExpansionFactory"/>
      </Catalog>
   </Node>
</TreeDef>
